<?php

define('MINECRAFT_LINKER_ENABLED', 1);
define('MINECRAFT_LINKER_IDENTITY', '');
define('MINECRAFT_MAX_UUIDS', 9);
define('MINECRAFT_NAME_ENABLED', 1);
define('MINECRAFT_ENABLE_ACTIVE_USER', 0);
define('MINECRAFT_LINKER_PASSWORD_ENABLED', 1);
define('MINECRAFT_LINKER_PASSWORD_KEY', '');
