<?php

define('MINECRAFT_LINKER_ENABLED', true);
define('MINECRAFT_LINKER_IDENTITY', '');
define('MINECRAFT_MAX_UUIDS', 0);
define('MINECRAFT_ENABLE_ACTIVE_USER', false);
define('MINECRAFT_LINKER_BRANDING', true);
